version: "3.9"

services:
  app:
    image: analyze-system/server
    container_name: analyze-server
    depends_on:
      - db
      - rdb
    network_mode: bridge
    volumes:
      - "./config:/app/config"
      - "./log:/app/log"
    ports:
      - "8888:8888"
    command: ./server
  appplus:
    build: .
    image: my_django_app:latest  # 你的Django应用镜像
    container_name: django_app
    command: gunicorn starwizAi.wsgi:application --bind 0.0.0.0:5177
    ports:
      - "5177:5177"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always
  db:
    image: postgres:latest
    container_name: analyze-db
    restart: always
    network_mode: bridge
    healthcheck:
      test: "exit 0"
    ports:
      - "54327:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=aidb
      - TZ=Asia/Shanghai
      - PGTZ=Asia/Shanghai
      - ALLOW_IP_RANGE=0.0.0.0/0
    volumes:
      - "./db/data:/var/lib/postgresql/data"
  redis:
      image: redis:7-alpine
      container_name: analyze-redis
      network_mode: bridge
      restart: always
      ports:
        - "6379:6379"
      command: [ "redis-server", "/etc/redis.conf", "--appendonly", "yes" ]
      volumes:
        - ./redis/data:/data
        - ./redis/redis.conf:/etc/redis.conf
      healthcheck:
        test: "redis-cli -h 127.0.0.1 -p 6379 info Replication"
        interval: 10s
        timeout: 5s
        retries: 3
        start_period: 10s
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    ports:
      - "80:80"
    depends_on:
      - web
    restart: always

  volumes:
    static-volume:
